version: '3.8'

services:
  mailslurper:
    image: marcopas/docker-mailslurper
    container_name: mail-server
    ports:
      - "2500:2500"
      - "8081:8080"
      - "8085:8085"
    restart: always
    command: [ ]

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

  spring-boot-app:
    build:
      context: ./
    container_name: EmailMFA
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis-server
      SPRING_REDIS_PORT: 6379
      SPRING_MAIL_HOST: mail-server
      SPRING_MAIL_PORT: 2500
      OTP_SECRET: HgaaZL2WF2tgTKRF6s7CUYipUysQPn20
    depends_on:
      - redis
      - mailslurper
    restart: always